# --- CONEXÃO COM O SUPABASE (POOLER / IPV4) ---

# 1. A URL Correta para Java (Porta 6543)
# Adicionei 'jdbc:' no começo e '?sslmode=require&prepareThreshold=0' no final
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# 2. O Usuário do Pooler (Tem que ser esse nome comprido mesmo!)
spring.datasource.username=postgres.thzzwvittdezrqokiodi

# 3. A SENHA (CUIDADO AQUI!) ?
# Remova os colchetes [ ] e coloque APENAS a senha.
# Se a senha for "batata123", coloque apenas: batata123
# NÃO coloque: [vem-mercado] (Isso parece ser o nome do projeto, não a senha)
spring.datasource.password=vem-mercado

# --- CONFIGURAÇÕES DO HIBERNATE ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect